site_name: TUD D120 Notizen

repo_url: https://github.com/anellie/fb20-notes
repo_name: "anellie/fb20-notes"
edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: purple
      accent: orange
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/anellie
    - icon: fontawesome/solid/globe 
      link: https://elia.garden
copyright: 2021 - 2022 by Ellie Leela

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - _js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://shynet.angm.xyz/ingress/5bc2faad-b177-4a2c-9efb-f7a08c291dec/script.js
